server:
  port: 0

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: king
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.catalog-microservice: DEBUG

