server:
  port: 0

spring:
  application:
    name: user-service
# 요 아래부터
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      name: user-service #여기에 특정 yml파일 명을 적는 것이 아니라 config-service의 프로젝트 명을 적으면 application.yml을 불러온다.
      profiles:
        active: default
# 요기까지 spring-cloud-config 외부에서 불러오기
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/datajpa
#    username: king
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  RabbitMQ 구독
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  RabbitMQ 구독 END --

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
greeting:
  message: Welcome to the Simple E-Commerce.

logging:
  level:
    com.example.usermicroservice.client: DEBUG

# actuator에서 사용할 수 있는 end포인트
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, busenv


