server:
  port: 8761 #discoveryservice? 8761 port?? ??

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # 11, 12?? : ?? ??? ???? ????? false? ??. ???? true
